import type { Metadata } from "next";
import { Work_Sans, Fira_Code } from "next/font/google";
import "./globals.css";

const workSans = Work_Sans({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-sans",
});

const firaCode = Fira_Code({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaCode.className} ${workSans.variable} ${firaCode.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
